/******************************************************************************
 * Mark Tengi
 * Written: Jun 18, 2013
 * 
 * Project Euler: Problem012 - Highly divisible triangular number
 * 
 * 
 * The sequence of triangle numbers is generated by adding the natural numbers.
 * So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first
 * ten terms would be:
 * 
 * 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
 * 
 * Let us list the factors of the first seven triangle numbers:
 * 
 *  1: 1
 *  3: 1,3
 *  6: 1,2,3,6
 * 10: 1,2,5,10
 * 15: 1,3,5,15
 * 21: 1,3,7,21
 * 28: 1,2,4,7,14,28
 * 
 * We can see that 28 is the first triangle number to have over five divisors.
 * 
 * What is the value of the first triangle number to have over five hundred
 * divisors?
 * 
 * 
 * Answer: 76576500
 * 
 *****************************************************************************/

public class Problem012 {
    // Algorithm stolen from PE user bartmeijer

    public static int countFactors(int i) {
        int fact = 0;
        for (int j = 1; j * j <= i; j++) {
            if (i % j == 0) {
                fact += 2;
                if (i == j * j) {
                    fact--;
                }
            }
        }
        return fact;
    }

    public static void main(String[] args) {
        int target = 500;
        long t = System.currentTimeMillis();
        for (int n = 1;; n++) {
            int count = 0;
            if (n % 2 == 0) {
                count = countFactors(n / 2) * countFactors(n + 1);
            } else {
                count = countFactors(n) * countFactors((n + 1) / 2);
            }
            if (count >= target) {
                System.out.println(n * (n + 1) / 2);
                break;
            }
        }
        System.out.println(System.currentTimeMillis() - t);
    }
}